In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df_test = pd.read_csv("customer_churn_dataset-training-master.csv")
df_train = pd.read_csv("customer_churn_dataset-testing-master.csv")

In [4]:
df_train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [5]:
df_test.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,2.0,30.0,Female,39.0,14.0,5.0,18.0,Standard,Annual,932.0,17.0,1.0
1,3.0,65.0,Female,49.0,1.0,10.0,8.0,Basic,Monthly,557.0,6.0,1.0
2,4.0,55.0,Female,14.0,4.0,6.0,18.0,Basic,Quarterly,185.0,3.0,1.0
3,5.0,58.0,Male,38.0,21.0,7.0,7.0,Standard,Monthly,396.0,29.0,1.0
4,6.0,23.0,Male,32.0,20.0,5.0,8.0,Basic,Monthly,617.0,20.0,1.0

In [6]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         64374 non-null  int64
 1   Age                64374 non-null  int64
 2   Gender             64374 non-null  object
 3   Tenure             64374 non-null  int64
 4   Usage Frequency    64374 non-null  int64
 5   Support Calls      64374 non-null  int64
 6   Payment Delay      64374 non-null  int64
 7   Subscription Type  64374 non-null  object
 8   Contract Length    64374 non-null  object
 9   Total Spend        64374 non-null  int64
 10  Last Interaction   64374 non-null  int64
 11  Churn              64374 non-null  int64
dtypes: int64(9), object(3)
memory usage: 5.9+ MB

In [7]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440833 entries, 0 to 440832
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CustomerID         440832 non-null  float64
 1   Age                440832 non-null  float64
 2   Gender             440832 non-null  object
 3   Tenure             440832 non-null  float64
 4   Usage Frequency    440832 non-null  float64
 5   Support Calls      440832 non-null  float64
 6   Payment Delay      440832 non-null  float64
 7   Subscription Type  440832 non-null  object
 8   Contract Length    440832 non-null  object
 9   Total Spend        440832 non-null  float64
 10  Last Interaction   440832 non-null  float64
 11  Churn              440832 non-null  float64
dtypes: float64(9), object(3)
memory usage: 40.4+ MB

In [8]:
print("the columns of training dataset:")
print(df_train.columns)
print("the columns of testing dataset:")
print(df_test.columns)
print("the shape of training dataset:")
print(df_train.shape)
print("the shape of testing dataset:")
print(df_test.shape)

the columns of training dataset:
Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')
the columns of testing dataset:
Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='object')
the shape of training dataset:
(64374, 12)
the shape of testing dataset:
(440833, 12)

In [9]:
print(df_train.isnull().sum())
print(df_test.isnull().sum())

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64
CustomerID           1
Age                  1
Gender               1
Tenure               1
Usage Frequency      1
Support Calls        1
Payment Delay        1
Subscription Type    1
Contract Length      1
Total Spend          1
Last Interaction     1
Churn                1
dtype: int64

In [10]:
df_test[df_test.isna().any(axis=1)]

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
199295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_test = df_test.drop(index=199295)

In [12]:
df_train["Gender"] = df_train["Gender"].map({
    "Male" : 1,
    "Female" : 0
})
df_test["Gender"] = df_test["Gender"].map({
    "Male" : 1,
    "Female" : 0
})

In [8]:
df_train = pd.get_dummies(
    df_train,
    columns = ["Subscription Type", "Contract Length"],
    dtype = int
)
df_test = pd.get_dummies(
    df_test,
    columns = ["Subscription Type", "Contract Length"],
    dtype = int
)

In [9]:
df_train.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Total Spend,Last Interaction,Churn,Subscription Type_Basic,Subscription Type_Premium,Subscription Type_Standard,Contract Length_Annual,Contract Length_Monthly,Contract Length_Quarterly
0,1,22,Female,25,14,4,27,598,9,1,1,0,0,0,1,0
1,2,41,Female,28,28,7,13,584,20,0,0,0,1,0,1,0
2,3,47,Male,27,10,2,29,757,21,0,0,1,0,1,0,0
3,4,35,Male,9,12,5,17,232,18,0,0,1,0,0,0,1
4,5,53,Female,58,24,9,2,533,18,0,0,0,1,1,0,0

In [14]:
df = pd.concat([df_train, df_test], ignore_index=True)

In [15]:
X = df.drop(columns = ["CustomerID", "Churn"])
Y = df["Churn"]

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split (
    X, 
    Y,
    test_size=0.2,
    stratify = Y,
    random_state = 42
)

print (X_train.shape)
print (X_test.shape)
print (Y_train.shape)
print (Y_test.shape)

(404164, 14)
(101042, 14)
(404164,)
(101042,)

In [17]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    n_jobs=-1,
    random_state=42
)

rf_model.fit(X_train, Y_train)

import joblib

joblib.dump(rf_model, "random_forest_model.pkl")

['random_forest_model.pkl']

In [18]:
rf_results = rf_model.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

accuracy = accuracy_score(Y_test, rf_results)
precision = precision_score(Y_test, rf_results)
recall = recall_score(Y_test, rf_results)
F1_score = f1_score(Y_test, rf_results)
matrix = confusion_matrix(Y_test, rf_results)

print("Accuracy: ", accuracy)
print("Precision: ", precision)
print("Recall: ", recall)
print("F1 Score: ", F1_score)
print("Confusion Matrix: ", matrix)

Accuracy:  0.9345816591120524
Precision:  0.8965528293722655
Recall:  0.9972370273979928
F1 Score:  0.9442184678222417
Confusion Matrix:  [[38488  6455]
 [  155 55944]]